Repository sparta-deligo/deligo, pull requests merged in 2025-03, with the labels that each got.

#18 [#7][#8] Menu CRUD 기능 구현
  src/main/java/com/example/deligo/common/exception/ExceptionType.java
  src/main/java/com/example/deligo/menu/controller/MenuController.java
  src/main/java/com/example/deligo/menu/dto/request/CreateMenuRequest.java
  src/main/java/com/example/deligo/menu/dto/request/UpdateMenuRequest.java
  src/main/java/com/example/deligo/menu/dto/response/MenuResponse.java
  src/main/java/com/example/deligo/menu/entity/Menu.java
  src/main/java/com/example/deligo/menu/repository/MenuRepository.java
  src/main/java/com/example/deligo/menu/service/MenuService.java
  src/main/java/com/example/deligo/order/repository/OrderRepository.java
Labels: 기능, 개발

#33 [Menu] UserId 어노테이션 적용 및 메뉴 삭제 시 확인 로직 추가
  src/main/java/com/example/deligo/common/exception/ExceptionType.java
  src/main/java/com/example/deligo/menu/controller/MenuController.java
  src/main/java/com/example/deligo/menu/service/MenuService.java
Labels: 기능, 리팩토링, 개발

#38 test: 주문 저장 로직 테스트 코드 구현
  src/test/java/com/example/deligo/order/service/orderServ/OrderServiceTest.java
Labels: 테스트

#39 메뉴 등록 Service 테스트 코드 작성
  src/main/java/com/example/deligo/menu/dto/request/CreateMenuRequest.java
  src/test/java/com/example/deligo/menu/service/MenuServiceTest.java
Labels: 테스트

#27 [#13] 가게 검색 / 인기 검색어 조회 기능 구현
  build.gradle
  src/main/java/com/example/deligo/search/controller/SearchController.java
  src/main/java/com/example/deligo/search/dto/PopularKeywordResponse.java
  src/main/java/com/example/deligo/search/service/SearchCacheService.java
  src/main/java/com/example/deligo/search/service/SearchService.java
  src/main/java/com/example/deligo/store/dto/response/StoreListResponse.java
  src/main/java/com/example/deligo/store/repository/StoreRepository.java
  src/main/java/com/example/deligo/store/service/StoreService.java
Labels: 기능, 개발
